name: scalable_cli
version: 0.0.1
description: A Scalable Command Line Interface for Flutter by JTD.
executables:
  scalable:

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  args: ^2.1.0
  cupertino_icons: ^1.0.5
  glob: ^2.0.2
  lcov_parser: ^0.1.2
  mason: ">=0.1.0-dev.26 <0.1.0-dev.27"
  mason_logger: ">=0.1.0-dev.13 <0.1.0-dev.14"
  meta: ^1.3.0
  path: ^1.8.0
  pub_updater: ^0.2.1
  pubspec_parse: ^1.2.0
  pubspec_yaml: ^3.1.0
  stack_trace: ^1.10.0
  universal_io: ^2.0.4
  very_good_test_runner: ^0.1.2

dev_dependencies:
  build_runner: ^2.0.0
  build_verify: ^3.0.0
  build_version: ^2.0.0
  flutter_lints: ^2.0.1
  mocktail: ^0.2.0
  test: ^1.17.0
