name: scalable_cli
version: 0.0.1
description: A Scalable Command Line Interface for Flutter by JTD.
executables:
  scalable:

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  args: ^2.3.1
  cupertino_icons: ^1.0.5
  glob: ^2.1.0
  lcov_parser: ^0.1.2
  mason: ">=0.1.0-dev.27 <0.1.0-dev.28"
  mason_logger: ">=0.1.0-dev.14 <0.1.0-dev.15"
  meta: ^1.8.0
  path: ^1.8.2
  pub_updater: ^0.2.2
  pubspec_parse: ^1.2.0
  pubspec_yaml: ^3.1.0
  recase: ^4.0.0
  stack_trace: ^1.10.0
  universal_io: ^2.0.4
  very_good_test_runner: ^0.1.2
  dart_style: ^2.2.3
  yaml_edit: ^2.0.3
  code_builder: ^4.1.0

dev_dependencies:
  build_runner: ^2.2.0
  build_verify: ^3.0.0
  build_version: ^2.1.1
  flutter_lints: ^2.0.1
  mocktail: ^0.3.0
  test: ^1.21.4
