// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: prefer_single_quotes, public_member_api_docs, lines_longer_than_80_chars, implicit_dynamic_list_literal, implicit_dynamic_map_literal

import 'package:mason/mason.dart';

final valueObjectBundle = MasonBundle.fromJson(<String, dynamic>{
  "files": [
    {
      "path": "lib/{{{path.pathCase()}}}/{{name.snakeCase()}}.dart",
      "data":
          "aW1wb3J0ICdwYWNrYWdlOnt7cHJvamVjdF9uYW1lfX0vY29yZS9jb3JlLmRhcnQnOwppbXBvcnQgJ3BhY2thZ2U6c2NhbGFibGUvZG9tYWluLmRhcnQnOwoKcGFydCAne3tuYW1lLnNuYWtlQ2FzZSgpfX0uZnJlZXplZC5kYXJ0JzsKCi8vLyB7QHRlbXBsYXRlIHt7bmFtZS5zbmFrZUNhc2UoKX19fQovLy8gKioqVmFsaWQqKio6Ci8vLwovLy8gVE9ETzogdmFsaWQgY2FzZXMKLy8vCi8vLyAtLS0KLy8vCi8vLyAqKipJbnZhbGlkKioqOgovLy8KLy8vIFRPRE86IGludmFsaWQgY2FzZXMKLy8vIHtAZW5kdGVtcGxhdGV9CmNsYXNzIHt7bmFtZS5wYXNjYWxDYXNlKCl9fXt7e2dlbmVyaWNzfX19IGV4dGVuZHMgVmFsdWVPYmplY3Q8e3t7dHlwZX19fT4gewogIEBvdmVycmlkZQogIGZpbmFsIEVpdGhlcjx7e25hbWUucGFzY2FsQ2FzZSgpfX1GYWlsdXJlLCB7e3t0eXBlfX19PiB2YWx1ZTsKCiAgLy8vIHtAbWFjcm8ge3tuYW1lLnNuYWtlQ2FzZSgpfX19CiAgZmFjdG9yeSB7e25hbWUucGFzY2FsQ2FzZSgpfX0oe3t7dHlwZX19fSByYXcpIHsKICAgIHJldHVybiB7e25hbWUucGFzY2FsQ2FzZSgpfX0uXyhfdmFsaWRhdGUocmF3KSk7CiAgfQoKICBjb25zdCB7e25hbWUucGFzY2FsQ2FzZSgpfX0uXyh0aGlzLnZhbHVlKTsKCiAgLy8vICoqKlJldHVybnMgW3Jhd10qKio6CiAgLy8vCiAgLy8vIFRPRE86IHZhbGlkIGNhc2VzCiAgLy8vCiAgLy8vIC0tLQogIC8vLwogIC8vLyAqKipSZXR1cm5zIFt7e25hbWUucGFzY2FsQ2FzZSgpfX1GYWlsdXJlXSoqKjoKICAvLy8KICAvLy8gVE9ETzogaW52YWxpZCBjYXNlcwogIHN0YXRpYyBFaXRoZXI8e3tuYW1lLnBhc2NhbENhc2UoKX19RmFpbHVyZSwge3t7dHlwZX19fT4gX3ZhbGlkYXRle3t7Z2VuZXJpY3N9fX0oe3t7dHlwZX19fSByYXcpIHsKICAgIC8vIFRPRE86IGltcGxlbWVudCB2YWxpZGF0aW9uCiAgICB0aHJvdyBVbmltcGxlbWVudGVkRXJyb3IoKTsKICB9CgogIEBvdmVycmlkZQogIFN0cmluZyB0b1N0cmluZygpID0+IHZhbHVlLmZvbGQoCiAgICAgICAgKGZhaWx1cmUpID0+ICd7e25hbWUucGFzY2FsQ2FzZSgpfX0oJGZhaWx1cmUpJywKICAgICAgICAodmFsdWUpID0+ICd7e25hbWUucGFzY2FsQ2FzZSgpfX0oJHZhbHVlKScsCiAgICAgICk7Cn0KCi8vLyBbVmFsdWVGYWlsdXJlXSB1bmlvbiB0aGF0IGJlbG9uZ3MgdG8gW3t7bmFtZS5wYXNjYWxDYXNlKCl9fV0uCkBmcmVlemVkCmNsYXNzIHt7bmFtZS5wYXNjYWxDYXNlKCl9fUZhaWx1cmV7e3tnZW5lcmljc319fSBleHRlbmRzIFZhbHVlRmFpbHVyZTx7e3t0eXBlfX19PgogICAgd2l0aCBfJHt7bmFtZS5wYXNjYWxDYXNlKCl9fUZhaWx1cmV7e3tnZW5lcmljc319fSB7CiAgY29uc3QgZmFjdG9yeSB7e25hbWUucGFzY2FsQ2FzZSgpfX1GYWlsdXJlLmZhaWx1cmVBKHsKICAgIHJlcXVpcmVkIHt7e3R5cGV9fX0gZmFpbGVkVmFsdWUsCiAgfSkgPSBfRmFpbHVyZUE7CiAgIGNvbnN0IGZhY3Rvcnkge3tuYW1lLnBhc2NhbENhc2UoKX19RmFpbHVyZS5mYWlsdXJlQih7CiAgICByZXF1aXJlZCB7e3t0eXBlfX19IGZhaWxlZFZhbHVlLAogIH0pID0gX0ZhaWx1cmVCOwp9Cg==",
      "type": "text"
    },
    {
      "path": "test/{{{path.pathCase()}}}/{{name.snakeCase()}}_test.dart",
      "data":
          "aW1wb3J0ICdwYWNrYWdlOnt7cHJvamVjdF9uYW1lfX0vY29yZS9jb3JlLmRhcnQnIGhpZGUgdGVzdDsKaW1wb3J0ICdwYWNrYWdlOnt7cHJvamVjdF9uYW1lfX0ve3t7cGF0aC5wYXRoQ2FzZSgpfX19L3t7bmFtZS5zbmFrZUNhc2UoKX19LmRhcnQnOwppbXBvcnQgJ3BhY2thZ2U6c2NhbGFibGVfdGVzdC9kb21haW5fdGVzdC5kYXJ0JzsKCnZvaWQgbWFpbigpIHsKICBncm91cCgne3tuYW1lLnBhc2NhbENhc2UoKX19JywgKCkgewogICAgbGF0ZSB7e3t0eXBlfX19IHJhdzsKCiAgICBzZXRVcCgoKSB7CiAgICAgIC8vIFNldCBkZWZhdWx0IHZhbHVlCiAgICAgIC8vIHJhdyA9IHZhbGlkIHZhbHVlOwogICAgfSk7CgogICAge3tuYW1lLnBhc2NhbENhc2UoKX19IGdldEluc3RhbmNlKCkgewogICAgICByZXR1cm4ge3tuYW1lLnBhc2NhbENhc2UoKX19KHJhdyk7CiAgICB9CgogICAgZ3JvdXAoJy4nLCAoKSB7CiAgICAgIGxhdGUge3tuYW1lLnBhc2NhbENhc2UoKX19IHVuZGVyVGVzdDsKCiAgICAgIHRlc3QoCiAgICAgICAgICAnR0lWRU4gcmF3IGlzIG5vdCB2YWxpZCcKICAgICAgICAgICdUSEVOIHJldHVybiBMZWZ0KDx7e25hbWUucGFzY2FsQ2FzZSgpfX1GYWlsdXJlPikuJywgKCkgewogICAgICAgIC8vIEFycmFuZ2UKICAgICAgICAvLyByYXcgPSBpbnZhbGlkIHZhbHVlCgogICAgICAgIC8vIEFjdAogICAgICAgIHVuZGVyVGVzdCA9IGdldEluc3RhbmNlKCk7CgogICAgICAgIC8vIEFzc2VydAogICAgICAgIC8vIGV4cGVjdCh1bmRlclRlc3QudmFsdWUsIGxlZnQoPHt7bmFtZS5wYXNjYWxDYXNlKCl9fUZhaWx1cmU+KSk7CiAgICAgIH0pOwoKICAgICAgLy8vIC4uLgoKICAgICAgdGVzdCgKICAgICAgICAgICdHSVZFTiByYXcgaXMgdmFsaWQnCiAgICAgICAgICAnVEhFTiByZXR1cm4gUmlnaHQocmF3KS4nLCAoKSB7CiAgICAgICAgLy8gQXJyYW5nZQogICAgICAgIC8vIHJhdyA9IHZhbGlkIHZhbHVlCgogICAgICAgIC8vIEFjdAogICAgICAgIHVuZGVyVGVzdCA9IGdldEluc3RhbmNlKCk7CgogICAgICAgIC8vIEFzc2VydAogICAgICAgIC8vIGV4cGVjdCh1bmRlclRlc3QudmFsdWUsIHJpZ2h0KHJhdykpOwogICAgICB9KTsKICAgIH0pOwoKICAgIGdyb3VwKCd0b1N0cmluZycsICgpIHsKICAgICAgU3RyaW5nIHVuZGVyVGVzdDsKCiAgICAgIHRlc3QoCiAgICAgICAgICAnR0lWRU4gcmF3IGlzIGludmFsaWQnCiAgICAgICAgICAnVEhFTiByZXR1cm4ge3tuYW1lLnBhc2NhbENhc2UoKX19KDx7e25hbWUucGFzY2FsQ2FzZSgpfX1GYWlsdXJlPiknLCAoKSB7CiAgICAgICAgLy8gQXJyYW5nZQogICAgICAgIC8vIHJhdyA9IGludmFsaWQgdmFsdWUKCiAgICAgICAgLy8gQWN0CiAgICAgICAgdW5kZXJUZXN0ID0gZ2V0SW5zdGFuY2UoKS50b1N0cmluZygpOwoKICAgICAgICAvLyBBc3NlcnQKICAgICAgICAvLyBleHBlY3QodW5kZXJUZXN0LCAne3tuYW1lLnBhc2NhbENhc2UoKX19KDx7e25hbWUucGFzY2FsQ2FzZSgpfX1GYWlsdXJlPiknKTsKICAgICAgfSk7CgogICAgICB0ZXN0KAogICAgICAgICAgJ0dJVkVOIHJhdyBpcyB2YWxpZCcKICAgICAgICAgICdUSEVOIHJldHVybiB7e25hbWUucGFzY2FsQ2FzZSgpfX0oPHZhbHVlPiknLCAoKSB7CiAgICAgICAgLy8gQXJyYW5nZQogICAgICAgIC8vIHJhdyA9IHZhbGlkIHZhbHVlCgogICAgICAgIC8vIEFjdAogICAgICAgIHVuZGVyVGVzdCA9IGdldEluc3RhbmNlKCkudG9TdHJpbmcoKTsKCiAgICAgICAgLy8gQXNzZXJ0CiAgICAgICAgLy8gZXhwZWN0KHVuZGVyVGVzdCwgJ3t7bmFtZS5wYXNjYWxDYXNlKCl9fSg8dmFsdWU+KScpOwogICAgICB9KTsKICAgIH0pOwogIH0pOwp9Cg==",
      "type": "text"
    }
  ],
  "hooks": [],
  "name": "value_object",
  "description": "A new brick created with the Mason CLI.",
  "version": "0.1.0+1",
  "environment": {"mason": ">=0.1.0-dev <0.1.0"},
  "readme": {
    "path": "README.md",
    "data":
        "IyB2YWx1ZV9vYmplY3QKCkEgbmV3IGJyaWNrIGNyZWF0ZWQgd2l0aCB0aGUgTWFzb24gQ0xJLgoKX0dlbmVyYXRlZCBieSBbbWFzb25dWzFdIPCfp7FfCgojIyBHZXR0aW5nIFN0YXJ0ZWQg8J+agAoKVGhpcyBpcyBhIHN0YXJ0aW5nIHBvaW50IGZvciBhIG5ldyBicmljay4KQSBmZXcgcmVzb3VyY2VzIHRvIGdldCB5b3Ugc3RhcnRlZCBpZiB0aGlzIGlzIHlvdXIgZmlyc3QgYnJpY2sgdGVtcGxhdGU6CgotIFtPZmZpY2lhbCBNYXNvbiBEb2N1bWVudGF0aW9uXVsyXQotIFtDb2RlIGdlbmVyYXRpb24gd2l0aCBNYXNvbiBCbG9nXVszXQotIFtWZXJ5IEdvb2QgTGl2ZXN0cmVhbTogRmVsaXggQW5nZWxvdiBEZW1vcyBNYXNvbl1bNF0KClsxXTogaHR0cHM6Ly9naXRodWIuY29tL2ZlbGFuZ2VsL21hc29uClsyXTogaHR0cHM6Ly9naXRodWIuY29tL2ZlbGFuZ2VsL21hc29uL3RyZWUvbWFzdGVyL3BhY2thZ2VzL21hc29uX2NsaSNyZWFkbWUKWzNdOiBodHRwczovL3Zlcnlnb29kLnZlbnR1cmVzL2Jsb2cvY29kZS1nZW5lcmF0aW9uLXdpdGgtbWFzb24KWzRdOiBodHRwczovL3lvdXR1LmJlL0c0UFRqQTZ0cFRVCgpUT0RPIHZhbHVlIG9iamVjdCB0ZXN0IGZhaWx1cmUgZGVzY3JpcHRpb24=",
    "type": "text"
  },
  "changelog": {
    "path": "CHANGELOG.md",
    "data": "IyAwLjEuMCsxCgotIFRPRE86IERlc2NyaWJlIGluaXRpYWwgcmVsZWFzZS4K",
    "type": "text"
  },
  "license": {
    "path": "LICENSE",
    "data": "VE9ETzogQWRkIHlvdXIgbGljZW5zZSBoZXJlLgo=",
    "type": "text"
  },
  "vars": {
    "project_name": {"type": "string"},
    "name": {"type": "string"},
    "path": {"type": "string"},
    "type": {"type": "string"},
    "generics": {"type": "string"}
  }
});
